# Generated by Django 4.1.3 on 2022-11-07 08:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('map', models.TextField(help_text='Сгенерировать яндекс-карту с любой меткой и вставить сюда через источник', verbose_name='Карта')),
                ('tel', models.CharField(help_text='Оформить по примеру: <a href="tel:Номер телефон с +7 и слитно">Номер телефона</a>', max_length=100, verbose_name='Телефон')),
                ('email', models.CharField(help_text='Оформить по примеру: <a href="mailto:Email">Email</a>', max_length=100, verbose_name='Email')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профиль',
            },
        ),
    ]
