# Generated by Django 4.1.3 on 2022-11-07 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profelepage', '0002_alter_userpage_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpage',
            name='email',
            field=models.CharField(max_length=100, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='userpage',
            name='tel',
            field=models.CharField(max_length=100, verbose_name='Телефон'),
        ),
    ]
