# Generated by Django 4.1.3 on 2022-11-07 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profelepage', '0003_alter_userpage_email_alter_userpage_tel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpage',
            name='map',
            field=models.TextField(default='Карта', help_text='Сгенерировать яндекс-карту с любой меткой и вставить сюда через источник', verbose_name='Карта'),
        ),
    ]
