# Generated by Django 4.1.3 on 2022-11-07 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profelepage', '0004_alter_userpage_map'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpage',
            name='email',
            field=models.CharField(default=1, max_length=100, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='userpage',
            name='map',
            field=models.TextField(default=1, help_text='Сгенерировать яндекс-карту с любой меткой и вставить сюда через источник', verbose_name='Карта'),
        ),
        migrations.AlterField(
            model_name='userpage',
            name='tel',
            field=models.CharField(default=1, max_length=100, verbose_name='Телефон'),
        ),
    ]
